steps:
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}",
        "${_SERVICE_FOLDER}",
      ]

  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"]

options:
  logStreamingOption: STREAM_ON

substitutions:
  _SERVICE_FOLDER: conferenceCalendar
  _SERVICE_NAME: conferenceCalendar-cloud-run

images:
  - "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"
